apiVersion: v1
kind: Pod
metadata:
    name: mypod-secret
    labels:
      app: mypod-secret
    annotations:
      sampleannotationkey: "i am dummy annotation value"
spec:
  volumes:
    - name: tls-certs
      secret:
        secretName: mypod-tls

  containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: mypod-secret
        volumeMounts:
          - name: tls-certs
            mountPath: /tls
            readOnly: true
  