apiVersion: v1
kind: Pod
metadata:
    name: mypod-config
    labels:
      app: mypod-config
    annotations:
      sampleannotationkey: "i am dummy annotation value"
spec:
  containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: mypod-config
        command:
          - "/kuard "
          - "${EXTRA_PARAM}"
        env:
          - name: ANOTHER_PARAM
            valueFrom:
              configMapKeyRef:
                name: myconfig
                key: extra-param

        volumeMounts:
          - name: config-volume
            mountPath: /config
  
  volumes:
    - name: config-volume
      configMap:
        name: myconfig

  restartPolicy: Never
