apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  namespace: kube-system

spec:
  
  selector:
    matchLabels:
      app: daemonpod

  template:
    metadata:
      labels:
        app: daemonpod
    spec:
      containers:
        - name: daemonpod
          image: "k8s.gcr.io/fluentd-elasticsearch:1.20"

