apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymypod

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypod

  template:
    metadata:
      labels:
        app: mypod

      annotations:
        kubernetes.io/change-cause: "Update to blue kuard."
    spec:
      containers:
        - name: mypod
          image: "gcr.io/kuar-demo/kuard-amd64:blue"
          imagePullPolicy: Always

