apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-west-2

nodeGroups:
  - name: node1
    instanceType: t2.micro
    desiredCapacity: 1
    ssh:
      publicKeyName: djaykey
  - name: node2-mixed
    minSize: 1
    maxSize: 2
    instancesDistribution:
      maxPrice: 0.2
      instanceTypes: ["t2.micro", "t2.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
    
    ssh:
      publicKeyName: djaykey