apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-west-2

nodeGroups:
  - name: node1
    minSize: 1
    maxSize: 2
    instanceType: t2.micro
    desiredCapacity: 1
    ssh:
      publicKeyName: djaykey
    
  - name: node2
    minSize: 0
    maxSize: 1
    instanceType: t2.micro
    desiredCapacity: 1
    ssh:
      publicKeyName: djaykey
