apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-west-2

nodeGroups:
  - name: node1
    instanceType: t2.micro
    desiredCapacity: 1
    ssh:
      publicKeyName: djaykey
    
